# Generated by Django 4.1 on 2022-08-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='ref',
            field=models.IntegerField(),
        ),
    ]
